spring.application.name=mycoolapp
coach.name=Mickey Mouse
team.name=The Mouse Club
# server.port=7070
# server.servlet.context-path=/mycoolapp

# Exposer tous les endpoints (par défaut, seul /health l'est)
management.endpoints.web.exposure.include=*
# Activer la lecture des propriétés info.* dans /actuator/info
management.info.env.enabled=true
info.app.name=My Super Cool App
info.app.description=A crazy fun app, yoohoo!
info.app.version=1.0.0